- name: Setting up Datadog agent
  hosts: webservers
  tasks:
    - name: "Create config path"
      file:
       path: /etc/datadog-agent/conf.d/http_check.d
       state: directory
       mode: 0755
       group: root
       owner: root
    - name: create config file from template
      ansible.builtin.template:
        src: datadog.yaml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.datadog

