---
redmine:
  db_postgres: private-db-ams-1-do-user-14683187-0.b.db.ondigitalocean.com
  db_port: 25060
  db_username: doadmin
  db_password: "{{ encrypted.db_password }}"
  db_database: defaultdb

website_url: devops.pimbi.icu
datadog_api_key: "{{ encrypted.datadog_api_key }}"
datadog_site: datadoghq.eu
datadog_checks:
  http_check:
    init_config:

    instances:
      - name: Hexlet DevOps Study website
        url: https://{{ website_url }}/
        method: GET
