- name: Deploy redmine
  hosts: all
  gather_facts: false
  serial: 1
  tasks:
    - name: create environment variables from template
      ansible.builtin.template:
        src: .env.template.j2
        dest: /var/tmp/redmine.env

    - name: run container
      community.docker.docker_container:
        name: redmine
        image: redmine
        env_file: /var/tmp/redmine.env
        state: started
        recreate: true
        restart_policy: unless-stopped
        ports:
          - 8080:3000
